server:
  port: 8009
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel_manage?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false

# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  #type-aliases-package: com.herocheer.school.sports.wechat.entity
  #启用自增主键
  global-config:
    db-config:
      id-type: auto
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true

  #限制上传文件大小
servlet:
  multipart:
    max-request-size: 1024MB
    max-file-size: 500MB

consumer:
  accessFilterPath: login
  algorithmName: md5
  hashIterations: 5